baseURL = "https://www.robert-jensen.dk"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Robert-Jensen.dk"
theme = "anatole"
summarylength = 50
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#DisqusShortname = "disqus_OsGKFX7o4i"

# Google Analytics
googleAnalytics = "UA-932020-4"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Robert-Jensen.dk"
author = "Robert Jensen"
description = "A place for my random ramblings. Mostly about VMware, Containers, DevOps etc. but not limited to that :-) "
profilePicture = "/images/profile.jpg"
keywords = "VMware, Blog, robert-jensen, Automation, DevOps, Python"
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["posts"]
images = ["images/thom-holmes-k-xKzowQRn8-unsplash.jpg"]
# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
copyright = "2019-2021"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/robertjensen/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/rhjensen79"

[[params.socialIcons]]
icon = "fab fa-gitlab"
title = "GitLab"
url = "https://gitlab.com/rhjensen79"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:robert@robert-jensen.dk"

[[params.socialIcons]]
icon = "fab fa-youtube"
title = "Youtube"
url = "https://www.youtube.com/channel/UCl04Gdm6a75l2GMzl86Tujg"

[[params.socialIcons]]
icon = "fab fa-docker"
title = "Docker"
url = "https://hub.docker.com/u/robertjensen"

[[params.socialIcons]]
icon = "fab fa-reddit"
title = "reddit"
url = "https://www.reddit.com/user/Rhjensen79"

## Menu items

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 1
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 2
  identifier = "about"
  url = "/about"